version: '3.8'

services:
  kvstore1:
    build: .
    container_name: kvstore1
    ports:
      - "9001:9000"

  kvstore2:
    build: .
    container_name: kvstore2
    ports:
      - "9002:9000"

  kvstore3:
    build: .
    container_name: kvstore3
    ports:
      - "9003:9000"

  kvstore4:
    build: .
    container_name: kvstore4
    ports:
      - "9004:9000"

  kvstore5:
    build: .
    container_name: kvstore5
    ports:
      - "9005:9000"
