version: '3.8'

services:
  kvstore1:
    build: .
    container_name: kvstore1
    networks:
      kvnet:
        ipv4_address: 172.16.238.11
    ports:
      - "9001:9000"

  kvstore2:
    build: .
    container_name: kvstore2
    networks:
      kvnet:
        ipv4_address: 172.16.238.12
    ports:
      - "9002:9000"

  kvstore3:
    build: .
    container_name: kvstore3
    networks:
      kvnet:
        ipv4_address: 172.16.238.13
    ports:
      - "9003:9000"

  kvstore4:
    build: .
    container_name: kvstore4
    networks:
      kvnet:
        ipv4_address: 172.16.238.14
    ports:
      - "9004:9000"

  kvstore5:
    build: .
    container_name: kvstore5
    networks:
      kvnet:
        ipv4_address: 172.16.238.15
    ports:
      - "9005:9000"

networks:
  kvnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
